# --------------------------------------------------------------
#
#
# Thanks for using MoarBows ;)
# Join my Discord here for fast support! https://discordapp.com/invite/7Pc8ZHh
#
#
# --------------------------------------------------------------

# If set to true, players must fully pull
# custom bows to be able to shoot arrows.
full-pull-restriction: false

# Particles displayed when holding a bow.
# Changing this requires /reload
# 'amount' is the amount of particles displayed at once.
# 'delay' is the delay between particles display. Using a higher
# delay will improve performance better than using a lower amount.
hand-particles:
    enabled: true
    amount: 2
    delay: 2

# Disables all crafting recipes of special bows.
# You can still obtain the bows via /mb get...
disable-bow-craftings: false

# When set to true, all special bows will be unbreakable.
unbreakable-bows: true

# Disables particles displayed by custom arrows.
arrow-particles: true

# Disables interactions with custom bows.
disable:
    repair: false
    craft: false
    enchant: false