# --------------------------------------------------------------
#
# Thanks for using MoarBows!
#
# --------------------------------------------------------------

# Notifies players with the 'moarbows.update-notify' perm node when
# they join the server if a new update is available for download.
# Requires /reload when changed.
update-notify: true

# If set to true, players must fully pull
# custom bows to be able to shoot arrows.
full-pull-restriction: false

# Particles displayed when holding a bow.
# Changing this requires /reload
# 'amount' is the amount of particles displayed at once.
hand-particles:
    enabled: true
    amount: 2

# Disables all crafting recipes of special bows.
# You can still obtain the bows via /mb get...
disable-bow-craftings: false

# Edit bow options here.
bow-options:
    unbreakable: true
    hide-unbreakable: true
    hide-enchants: false

# Disables particles displayed by custom arrows.
arrow-particles: true

# Disables interactions with custom bows.
# Only players with specific perm nodes will be able to
# perform these actions (moarbows.repair & moarbows.enchant).
disable:
    repair: true
    enchant: true
