name: MoarBows
version: 2.3
main: net.Indyuce.moarbows.MoarBows
author: Indyuce
softdepend: [WorldGuard]
commands:
    moarbows:
        description: Main command.
        aliases: [mb, bows]
permissions:
    moarbows.admin:
        description: Main permission.
        default: op
    moarbows.gui:
        description: Access the bows GUI.
        default: op
    moarbows.anvil:
        description: Allows to create a bow by renaming a regular one.
        default: op
    moarbows.repair:
        description: Allows to repair a special bow.
        default: op
    moarbows.enchant:
        description: Allows to repair a special bow.
        default: op
    moarbows.use.*:
        description: Use all special bows.
        default: op
        children:
            moarbows.use.silver_bow: true
            moarbows.use.explosive_bow: true
            moarbows.use.shocking_bow: true
            moarbows.use.corrosive_bow: true
            moarbows.use.hunter_bow: true
            moarbows.use.marked_bow: true
            moarbows.use.lightning_bowlt: true
            moarbows.use.void_bow: true
            moarbows.use.ice_bow: true
            moarbows.use.fire_bow: true
            moarbows.use.trippple_bow: true
            moarbows.use.composite_bow: true
            moarbows.use.gravity_bow: true
            moarbows.use.cupidons_bow: true
            moarbows.use.linear_bow: true
            moarbows.use.railgun_bow: true
            moarbows.use.flare_bow: true
            moarbows.use.wither_bow: true
            moarbows.use.snow_bow: true
            moarbows.use.autobow: true
            moarbows.use.shadow_bow: true
            moarbows.use.chicken_bow: true
            moarbows.use.blaze_bow: true
            moarbows.use.meteor_bow: true
            moarbows.use.pulsar_bow: true
            moarbows.use.spartan_bow: true
            moarbows.use.earthquake_bow: true